CREATE TABLE "SYSDBA"."PRICE_INFO"
(
"ID" VARCHAR(64) NOT NULL,
"COAL_PRICE" REAL,
"WATER_PRICE" REAL,
"ENABLE_DATE" DATE,
"STATUS" CHAR(1),
"IS_ENABLE_DELETE" CHAR(1) DEFAULT 1,
"OPERATE_TIME" DATETIME(0),
"OPERATOR_ID" VARCHAR(36),
"OPERATOR_NAME" VARCHAR(36),
"IS_DELETE" CHAR(1) DEFAULT 0,
CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "SYSDBA"."PRICE_INFO" IS '价格信息表';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."COAL_PRICE" IS '实时煤价';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."WATER_PRICE" IS '实时水价';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."ENABLE_DATE" IS '启用日期';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."STATUS" IS '状态0：未启用 1：启用';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."IS_ENABLE_DELETE" IS '是否可删：0：否，1：是';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."OPERATE_TIME" IS '操作时间';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."OPERATOR_ID" IS '操作人id';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."OPERATOR_NAME" IS '操作人姓名';
COMMENT ON COLUMN "SYSDBA"."PRICE_INFO"."IS_DELETE" IS '是否删除 0：否 1：是';